// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnelwwrqvmpxnltvfpar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuZWx3d3Jxdm1weG5sdHZmcGFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTYyODYsImV4cCI6MjA3MDk5MjI4Nn0.Mo0qkpTLSViwepUg9RDyTicazdIVhPO6Tdm3xMjW0R0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});